name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Extension
        run: npm run build

      - name: Package Extension (ZIP)
        run: |
          cd dist
          zip -r ../localmask-extension.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: localmask-extension
          path: localmask-extension.zip
          retention-days: 90
